easy_admin:
    # On définit le nom de l'interface d'administration
    site_name: 'Coronavirus'
    # On définit l'affichage de l'utilisateur
    user:
        display_name: true
        display_avatar: true
    design:
        # Ces lignes sont utiles pour CKEditor
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
        # Ces lignes définiront notre menu
        menu:
            # - { label: 'Articles' }
            - { entity: 'IdeaProposition', label: 'IdeaProposition', icon: 'book' }
            - { entity: 'User', label: 'User', icon: 'book' }
            - { entity: 'NoteHistory', label: 'NoteHistory', icon: 'book' }
            - { entity: 'Message', label: 'Message', icon: 'book' }
            - { entity: 'Room', label: 'Room', icon: 'book' }
            # - { entity: 'Room', label: 'Catégories', icon: 'tag' }
            # - { entity: 'NotHistory', label: 'Mots Clés', icon: 'tag' }
            # - { label: 'Utilisateurs' }
            # - { entity: 'Message', label: 'Utilisateurs', icon: 'user' }
            
    formats:
        # Ici on définit le format des dates
        datetime: 'd/m/Y à H:i'
    entities:
        IdeaProposition:
            # Correspond au fichier IdeaProposition.php
            class: App\Entity\IdeaProposition
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - title
                    # Le champ ci-dessous affichera l'image de l'article
                    - { property: 'featuredImage', label: 'Image', type: 'image', base_path: '%app.path.featured_images%' }
                    - { property: 'date', label: 'Créé' }
                    # Les catégories et les mots-clé sont listés ci-dessous
                    - { property: 'user', label: 'user'}
                    - noteHistories
                sort: ['date', 'desc']
            # On définit ci-dessous le contenu du formulaire d'ajout ou modification d'article
            form:
                fields:
                    - title
                    # Affichage de l'éditeur Wysiwyg
                    - { property: 'content', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
                    # Affichage du champ d'ajout d'image
                    - { property: 'imageFile', type: 'vich_image', label: 'Image' }
                    - totalScore
                    - user
                    - noteHistories

                    
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - first_name
                    - last_name
                    - email
                    - username
                
            form:
                fields:
                    - first_name
                    - last_name
                    - email
                    - username
                    - adress
                    - city
                    - country
                    - ideaPropositions
                    - noteHistories
                    - messages
                    - { property: 'roles', label: 'Rôles', type: choice, type_options: {expanded: true, multiple: true, choices: {'Utilisateur':'ROLE_USER', 'Administrateur':'ROLE_ADMIN'}}}
        NoteHistory:

            class: App\Entity\NoteHistory

        Message:

            class: App\Entity\Message
        Room:
            class: App\Entity\Room
            list:
                fields:
                    - id
                    - title
                    - type
                    - creationDate
                    
                
            form:
                fields:
                    - title
                    - type    
                    - messages
                    - ideaProposition

