language: php
php:
  - '7.4.5'

script:
   - composer install
   - composer require --dev symfony/phpunit-bridge
   - composer update
   - yarn install
   - yarn build
   - php bin/console d:d:c
   - php bin/console doctrine:schema:update --force
   - php bin/console hautelook:fixtures:load
   
   
services:
  - mysql
