before:
  path: /{_locale}
  controller: App\Controller\AccueilController::index
  defaults: {_locale: fr}
  requirements:
    _locale: en|fr

index:
    path: /{_locale}
    controller: App\Controller\AccueilController::index
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

admin:
    path: /{_locale}
    controller: App\Controller\AccueilController::index
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

login:
    path: /{_locale}
    controller: App\Controller\SecurityController::index
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr

register:
    path: /{_locale}
    controller: App\Controller\RegistrationController::index
    defaults: {_locale: fr}
    requirements:
      _locale: en|fr